# Generated by Django 4.1.4 on 2022-12-19 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cenima', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='fourth_time_showing',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='shows',
            name='image_link',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='shows',
            name='link',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='shows',
            name='second_time_showing',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='shows',
            name='third_time_showinng',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='shows',
            name='time_showing',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
