# Generated by Django 4.1.4 on 2022-12-19 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cenima', '0002_alter_shows_fourth_time_showing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='fourth_time_showing',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='shows',
            name='second_time_showing',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='shows',
            name='third_time_showinng',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='shows',
            name='time_showing',
            field=models.DateTimeField(),
        ),
    ]
